stages:
  - test
  - validate
  - deploy
  - deploy_fargate
  - build_cli
  - destroy

variables:
  AWS_REGION: "us-east-2"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      variables:
        TF_STATE_NAME: "development-deployment"
      when: always
    - if: '$CI_COMMIT_BRANCH == "prod" && $CI_PIPELINE_SOURCE == "push"'
      variables:
        TF_STATE_NAME: "production-deployment"
      when: always
    - when: never

# test_ndnp_open_ocr:
#   stage: test
#   image: docker:24.0.2
#   services:
#     - docker:24.0.2-dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#     DOCKER_BUILDKIT: 1
#   before_script:
#     - apk add --no-cache bash
#   script:
#     - docker build --platform linux/amd64 --build-arg INCLUDE_TEST_DEPS=true -t ndnp-open-ocr-test ./packages/ndnp_open_ocr
#     - docker run --rm --platform linux/amd64 ndnp-open-ocr-test pytest

validate:
  image:
    name: hashicorp/terraform:1.5.0
    entrypoint: [""]
  stage: validate
  variables:
    TF_VAR_env: $TF_STATE_NAME
    TF_STATE_KEY: "env:/ndnp-open-ocr-${TF_STATE_NAME}/ndnp-open-ocr-tf-state-files/dev/terraform.tfstate"
  before_script:
    - terraform init -force-copy
    - terraform workspace select ndnp-open-ocr-$TF_STATE_NAME || terraform workspace new ndnp-open-ocr-$TF_STATE_NAME
  script:
    - terraform fmt -check
    - terraform validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      when: on_success
    - when: never


# Consolidated Terraform Deployment
deploy:
  image:
    name: hashicorp/terraform:1.5.0
    entrypoint: [""]
  stage: deploy
  variables:
    TF_VAR_env: $TF_STATE_NAME
    S3_BUCKET: "ndnp-open-ocr-dependencies"
    TF_STATE_KEY: "env:/ndnp-open-ocr-${TF_STATE_NAME}/ndnp-open-ocr-tf-state-files/dev/terraform.tfstate"
  before_script:
    - terraform init -force-copy
    - terraform workspace select ndnp-open-ocr-$TF_STATE_NAME || terraform workspace new ndnp-open-ocr-$TF_STATE_NAME
  script:
    - terraform apply -input=false -auto-approve
    - export ECR_REPO_URI=$(terraform output -raw ecr_repo_url)
  artifacts:
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      when: on_success
    - when: never

# Docker Build and Push for Fargate Deployment
deploy_fargate:
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  stage: deploy_fargate
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  dependencies:
    - deploy
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - python3 -m venv /tmp/venv
    - . /tmp/venv/bin/activate
    - pip install awscli
    - export AWS_REGION=${AWS_REGION:-"us-east-2"}
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 342134162356.dkr.ecr.us-east-2.amazonaws.com
    - docker build --platform linux/amd64 -t ndnp_open_ocr:latest ./packages/ndnp_open_ocr
    - docker tag ndnp_open_ocr:latest 342134162356.dkr.ecr.us-east-2.amazonaws.com/ndnp-open-ocr-container-repo-${TF_STATE_NAME}:latest
    - docker push 342134162356.dkr.ecr.us-east-2.amazonaws.com/ndnp-open-ocr-container-repo-${TF_STATE_NAME}:latest
  environment:
    name: $TF_STATE_NAME
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      when: on_success
    - when: never

# Python CLI Build Job
build_cli:
  image: python:3.9
  stage: build_cli
  variables:
    OUTPUT_BUCKET_NAME: "ndnp-open-ocr-output-bucket-${TF_STATE_NAME}"
    SCHEDULER_ARN: "arn:aws:lambda:us-east-2:420280634985:function:ndnp-open-ocr-scheduler-lambda-function-${TF_STATE_NAME}"
    GET_JOB_ARN: "arn:aws:lambda:us-east-2:420280634985:function:ndnp-open-ocr-get-job-lambda-function-${TF_STATE_NAME}"
  script:
    - pip install poetry
    - cd packages/cli/
    # Inject stage-specific variables into a config file
    - echo "OUTPUT_BUCKET_NAME = '${OUTPUT_BUCKET_NAME}'" > ndnp_openocr/config.py
    - echo "SCHEDULER_ARN = '${SCHEDULER_ARN}'" >> ndnp_openocr/config.py
    - echo "GET_JOB_ARN = '${GET_JOB_ARN}'" >> ndnp_openocr/config.py
    - poetry build
    - poetry config http-basic.gitlab-ci-token ${CI_JOB_TOKEN} gitlab-ci-token
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    # Publish the package to the GitLab Package Registry. The deployment process currently requires manual installation and upgrading
    # of the deployed CLI tool on NDNPQR. This will be automated in the future.
    # To install the latest package on NDNPQR after it has been published with the line below, I simply run
    # pip install --upgrade
    - poetry publish --repository gitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      when: on_success
    - when: never

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  dependencies:
    - deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      when: manual
    - when: never
