include:
  - template: Terraform/Base.gitlab-ci.yml  # Includes Terraform boilerplate
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # Includes security analysis templates

stages:
  - validate
  - test
  - build
  - deploy
  - dev
  - cleanup
  - package

variables:
  ECR_REPO_URI_DEV: "342134162356.dkr.ecr.us-east-2.amazonaws.com/ndnp-open-ocr-container-repo-dev"
  ECR_REPO_URI_STAGING: "342134162356.dkr.ecr.us-east-2.amazonaws.com/ndnp-open-ocr-container-repo-staging"
  ECR_REPO_URI_PROD: "342134162356.dkr.ecr.us-east-2.amazonaws.com/ndnp-open-ocr-container-repo-prod"
  $TF_STATE_NAME: "dev"

docker_build_and_push:
  image: docker:latest
  services:
    - docker:24.0.2-dind
  stage: deploy
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - python3 -m venv /tmp/venv
    - . /tmp/venv/bin/activate

    # Install AWS CLI in virtual environment
    - pip install awscli

    # Set AWS region if not already set
    - export AWS_REGION=${AWS_REGION:-"us-east-2"}

  script:
    - |
      if [ "$TF_STATE_NAME" == "dev" ]; then
        export ECR_REPO_URI=$ECR_REPO_URI_DEV
      elif [ "$TF_STATE_NAME" == "staging" ]; then
        export ECR_REPO_URI=$ECR_REPO_URI_STAGING
      elif [ "$TF_STATE_NAME" == "prod" ]; then
        export ECR_REPO_URI=$ECR_REPO_URI_PROD
      fi
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI_DEV
    - docker build --platform linux/amd64 -t ndnp_open_ocr:latest ./packages/ndnp_open_ocr
    - docker build --platform linux/amd64 -t ndnp-open-ocr-container-repo:latest ./packages/ndnp_open_ocr_fargate_deployment
    - docker tag ndnp-open-ocr-container-repo:latest $ECR_REPO_URI_DEV:latest
    - docker push $ECR_REPO_URI_DEV:latest
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME


fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

# Terraform build stage
build:
  extends: .terraform:build

# Deployment stage from boilerplate
deploy:
  extends: .terraform:deploy
  dependencies:
    - build
    - docker_build_and_push
  environment:
    name: $TF_STATE_NAME

# Python CLI Build Job
package:
  image: python:3.9
  stage: package
  script:
    - pip install poetry
    - cd packages/cli/
    - poetry build
    - poetry config http-basic.gitlab-ci-token ${CI_JOB_TOKEN} gitlab-ci-token
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --repository gitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - packages/cli/**/*
      when: always

# Terraform Dev Environment
deploy_dev:
  image:
    name: hashicorp/terraform:1.5.0
    entrypoint: [""]

  stage: dev
  dependencies:
    - build
  before_script:
    - terraform init -input=false -backend-config="address=https://git.loc.gov/api/v4/projects/2983/terraform/state/development" -backend-config="lock_address=https://git.loc.gov/api/v4/projects/2983/terraform/state/development/lock" -backend-config="unlock_address=https://git.loc.gov/api/v4/projects/2983/terraform/state/development/lock" -backend-config="username=gitlab-ci-token" -backend-config="password=${CI_JOB_TOKEN}"
  script:
     - terraform apply -input=false -auto-approve
  artifacts:
    when: always
  when: always
