include:
  - template: Terraform/Base.gitlab-ci.yml  # Includes Terraform boilerplate
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # Includes security analysis templates

stages:
  - validate
  - test
  - build
  - deploy
  - deploy_fargate
  - cleanup
  - package
  - build_cli
  - destroy

variables:
  AWS_REGION: "us-east-2"
  TF_STATE_NAME: "prod1"

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

# Consolidated Terraform Deployment
deploy:
  image:
    name: hashicorp/terraform:1.5.0
    entrypoint: [""]

  stage: deploy
  variables:
    TF_VAR_env: $TF_STATE_NAME
  extends: .terraform:deploy
  before_script:
    # - |
    #   if [ "$CI_COMMIT_BRANCH" == "main" ]; then
    #     export TF_STATE_NAME="development"
    #   elif [ "$CI_COMMIT_BRANCH" == "prod" ]; then
    #     export TF_STATE_NAME="prod"
    #   else
    #     export TF_STATE_NAME="development"
    #   fi
    - |
      terraform init -input=false \
        - backend-config="address=https://git.loc.gov/api/v4/projects/2983/terraform/state/${TF_STATE_NAME}" \
        - backend-config="lock_address=https://git.loc.gov/api/v4/projects/2983/terraform/state/${TF_STATE_NAME}/lock" \
        - backend-config="unlock_address=https://git.loc.gov/api/v4/projects/2983/terraform/state/${TF_STATE_NAME}/lock" \
        - backend-config="username=gitlab-ci-token" \
        - backend-config="password=${CI_JOB_TOKEN}" \
        - backend-config="lock_method=POST" \
        - backend-config="unlock_method=DELETE" \
        - backend-config="retry_wait_min=5"
  script:
    - terraform apply -input=false -auto-approve

    # Extract the ECR repository URI and save it for the next stage
    - export ECR_REPO_URI=$(terraform output -raw ecr_repo_url)
  # rules:
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "prod" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    when: always
  rules:
    - when: always

# Docker Build and Push for Fargate Deployment
deploy_fargate:
  image: docker:latest
  services:
    - docker:24.0.2-dind
  stage: deploy_fargate
  dependencies:
    - deploy
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - python3 -m venv /tmp/venv
    - . /tmp/venv/bin/activate

    # Install AWS CLI in virtual environment
    - pip install awscli

    # Set AWS region if not already set
    - export AWS_REGION=${AWS_REGION:-"us-east-2"}
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 342134162356.dkr.ecr.us-east-2.amazonaws.com
    - docker build --platform linux/amd64 -t ndnp_open_ocr:latest ./packages/ndnp_open_ocr
    - docker tag ndnp_open_ocr:latest $ECR_REPO_URI:latest
    - docker push $ECR_REPO_URI:latest
  environment:
    name: $TF_STATE_NAME

# Python CLI Build Job
build_cli:
  image: python:3.9
  stage: build_cli
  script:
    - pip install poetry
    - cd packages/cli/
    - poetry build
    - poetry config http-basic.gitlab-ci-token ${CI_JOB_TOKEN} gitlab-ci-token
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --repository gitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - packages/cli/**/*
      when: always

destroy:
  stage: destroy
  script:
    - terraform destroy  -auto-approve
  dependencies:
    - deploy
  when: manual
