import boto3
import click
import requests
from ndnp_openocr.helpers import sync_s3_batch, find_missing_pdfs
import json
import time
import logging
import os

logger = logging.getLogger(__name__)


@click.group()
@click.pass_context
def cli(ctx):
    """Initialize command line interface with context settings for bucket, queue, and scheduler ARN."""
    # Initialize the context dict (these probably should somehow be populated by Terraform in the future...)
    ctx.ensure_object(dict)
    # Store bucket in the context (change to ndnp-open-ocr-output-bucket-test for testing purposes)
    ctx.obj["INPUT_BUCKET_NAME"] = "ndnp-open-ocr-output-bucket-test-2"
    ctx.obj["OUTPUT_BUCKET_NAME"] = "ndnp-open-ocr-output-bucket-test-2"
    # ctx.obj[
    #     "QUEUE_URL"
    # ] = "https://sqs.us-east-1.amazonaws.com/342134162356/ndnp-open-ocr-queue"
    # ctx.obj[
    #     "SCHEDULER_ARN"
    # ] = "arn:aws:lambda:us-east-2:342134162356:function:ndnp-open-ocr-scheduler-lambda-function-dev"
    ctx.obj[
        "SCHEDULER_ARN"
    ] = "arn:aws:lambda:us-east-2:420280634985:function:ndnp-open-ocr-scheduler-lambda-function-dev"
    ctx.obj[
        "GET_JOB_ARN"
    ] = "arn:aws:lambda:us-east-2:342134162356:function:ndnp-open-ocr-get-job-lambda-function-dev"


@click.command()
@click.option("--prefix", default="", help="The prefix in S3 bucket to filter files.")
@click.option(
    "--output-dir", default=".", help="The directory to output the new files to."
)
@click.option(
    "--overwrite", is_flag=True, default=False, help="Overwrite existing files."
)
@click.option("--local-batch", default="", help="The path to local batch data.")
@click.pass_context
def sync(ctx, job: str, output_dir: str, overwrite: bool, local_batch: str):
    """Creates a copy of a local NDNP batch, and replaces old PDFs and ALTO files with new PDFs and ALTOs generated by NDNP Open OCR pipeline (outputted to S3)."""

    # Get bucket from the context
    bucket = ctx.obj["OUTPUT_BUCKET_NAME"]
    print(bucket)
    sync_s3_batch(bucket, job, output_dir, overwrite, local_batch)


def reprocess_batch(ctx, batch_name: str, bucket: str):
    """Kicks off reprocessing job for a certain S3 NDNP batch."""
    lambda_client = boto3.client("lambda", region_name="us-east-2")
    # This is the prefix from the loc-preservation bucket...should stick to this if we can.
    if bucket == "loc-preservation":
        prefix = os.path.join("loc-preservation/lcbp/ndnp/dlc/", batch_name)
    else:
        prefix = batch_name
    payload = {
        "pathParameters": {
            "prefix": prefix,
            "bucketName": bucket,
        }
    }
    print(payload)
    try:
        # Async invoke the scheduler Lambda function passing the prefix and bucket name
        # as path parameters (modeled from API Gateway request, should be changed later).
        response = lambda_client.invoke(
            FunctionName=ctx.obj["SCHEDULER_ARN"],
            InvocationType="RequestResponse",
            Payload=json.dumps(payload).encode("utf-8"),
        )

        print(response)
        response_payload = json.loads(response["Payload"].read())

        print(response_payload)

    except Exception as e:
        print(f"Failed to trigger Lambda function: {e}")

    return ctx


@click.command()
@click.option(
    "--batch_name",
    default="",
    help="The batch_name in loc-preservation bucket to reprocess.",
)
@click.option(
    "--bucket", default="loc-preservation", help="The s3 bucket that the batch is located in."
)
@click.pass_context
def reprocess(ctx, batch_name: str, bucket: str):
    """Command to kick off reprocessing job for a certain S3 NDNP batch."""
    ctx = reprocess_batch(ctx, batch_name, bucket)


@click.command()
@click.option("--job", default="", help="The prefix in the output bucket")
@click.pass_context
def get_missing(ctx, job: str):
    """List files missing from S3 output bucket. The output prefix can be used
    to surmise the original input prefix. This isn't used with test bucket at the moment

    The design of job (id) is essentially PREVIOUS_BATCH_NAME__UUID, that's how we know. In addition,
    LOC Preservation bucket will be prefixed with predetermined string.

    """

    input_prefix = job.split("__")[0]

    missing_pdfs = find_missing_pdfs(
        ctx.obj["INPUT_BUCKET_NAME"],
        input_prefix,
        ctx.obj["OUTPUT_BUCKET_NAME"],
        job,
    )
    print(missing_pdfs)


@click.command()
@click.option(
    "--job", default="", help="The job_id of the NDNP Open OCR Reprocessing Job."
)
@click.pass_context
def check_status(ctx, job: str):
    """Check status of batch processing job"""
    # Initialize DynamoDB resource
    lambda_client = boto3.client("lambda")
    # This is the prefix from the loc-preservation bucket...should stick to this if we can.
    payload = {
        "pathParameters": {
            "JobId": job,
        }
    }
    try:
        # Async invoke the scheduler Lambda function passing the prefix and bucket name
        # as path parameters (modeled from API Gateway request, should be changed later).
        response = lambda_client.invoke(
            FunctionName=ctx.obj["GET_JOB_ARN"],
            InvocationType="RequestResponse",
            Payload=json.dumps(payload).encode("utf-8"),
        )
        response_payload = json.loads(response["Payload"].read())

        num_pdfs_remaining = response_payload["RemainingPDFMessages"]
        num_altos_remaining = response_payload["RemainingALTOMessages"]

        print(num_altos_remaining, " ALTO files remaining to be processed")
        print(num_pdfs_remaining, " PDFs remaining to be processed.")

    except Exception as e:
        print(f"Failed to trigger Lambda function: {e}")

    return ctx


cli.add_command(sync)
cli.add_command(reprocess)
cli.add_command(get_missing)
cli.add_command(check_status)

if __name__ == "__main__":
    cli()
