import boto3
import click
import requests
from .helpers import sync_s3_batch
from rich import print
from rich.console import Console
import json
import time
import logging
import os
from botocore.config import Config
import keyring
import shutil

# Import the generated config file with injected values
from . import config

CONFIG_KEYS = ["job_id", "output_dir"]


def initialize_config():
    """Initialize the configuration dictionary from keyring or set defaults."""
    config_dict = {
        "OUTPUT_BUCKET_NAME": config.OUTPUT_BUCKET_NAME,
        "SCHEDULER_ARN": config.SCHEDULER_ARN,
        "GET_JOB_ARN": config.GET_JOB_ARN,
    }
    # Load other config values from keyring as needed
    for key in CONFIG_KEYS:
        config_dict[key] = keyring.get_password("ndnp_openocr", key)
    return config_dict


def reprocess_batch(ctx, batch_name: str, bucket: str, segmentation: bool, img_extension: str = None):
    """Kicks off reprocessing job for a certain S3 NDNP batch.

    Parameters
    ----------
    segmentation: bool
        Flag to indicate whether the OCR job should run in segmentation mode.
    img_extension: str
        Image file extension to process: "jp2" or "tif" (default: tif).
    """
    lambda_client = boto3.client(
        "lambda",
        region_name=config.AWS_REGION,
        config=Config(
            read_timeout=900,  # Time in seconds
            connect_timeout=10,  # Time in seconds
        ),
    )
    query_params = {"use_segmenter": str(segmentation).lower()}
    if img_extension:
        query_params["img_extension"] = img_extension

    payload = {
        "pathParameters": {
            "batchName": batch_name,
            "bucketName": bucket,
        },
        "queryStringParameters": query_params,
    }
    try:
        # Async invoke the scheduler Lambda function passing the prefix and bucket name
        # as path parameters (modeled from API Gateway request, should be changed later).
        response = lambda_client.invoke(
            FunctionName=ctx.obj['config']["SCHEDULER_ARN"],
            InvocationType="RequestResponse",
            Payload=json.dumps(payload).encode("utf-8"),
        )

        response_payload = json.loads(response["Payload"].read())
        print(response_payload)

        body = json.loads(response_payload["body"])
        job_id = body["job"]

        keyring.set_password("ndnp_openocr", "job_id", job_id)

        print(
            '\n🚀 [green]Job successfully kicked off for "{}" batch in "{}" bucket'.format(
                batch_name, bucket
            )
        )

        print(
            "\n [bold cyan] To check status of the job, run: \n ndnp_openocr get --job {}".format(
                job_id
            )
        )

    except Exception as e:
        print(f"Failed to trigger Lambda function: {e}")

    return ctx


@click.group()
@click.pass_context
def cli(ctx):
    """Initialize command line interface with context settings for bucket, queue, and scheduler ARN."""
    # Initialize the context dict (these probably should somehow be populated by Terraform in the future...)
    ctx.ensure_object(dict)
    ctx.obj["config"] = initialize_config()


@click.command()
@click.option("--job", default="", help="The prefix in S3 bucket to filter files.")
@click.option(
    "--output-dir", default=".", help="The directory to output the new files to."
)
@click.option("--local-batch", default="", help="The path to local batch data.")
@click.pass_context
def sync(ctx, job, output_dir, local_batch):
    """Creates a copy of a local NDNP batch, and replaces old PDFs and ALTO files with new PDFs and ALTOs generated by NDNP Open OCR pipeline (outputted to S3)."""
    config = ctx.obj["config"]
    # Use values from config if arguments not provided
    job = job or config.get("job_id")
    output_dir = output_dir or config.get("output_dir") or "."

    if job:
        print(f"[green]Using job ID: {job}")
        # Update config and keyring
        config["job_id"] = job
        keyring.set_password("ndnp_openocr", "job_id", job)
    else:
        print("[red]No job ID provided or found. Exiting.")
        return

    if output_dir:
        # Update config and keyring
        config["output_dir"] = output_dir
        keyring.set_password("ndnp_openocr", "output_dir", output_dir)
        print(f"[green]Using output directory: {output_dir}")

    # Proceed with the command's main functionality
    bucket = ctx.obj['config']["OUTPUT_BUCKET_NAME"]
    sync_s3_batch(bucket, job, local_batch, output_dir)


@click.command()
@click.option(
    "--job",
    default=None,
    help="The job ID. If not provided, the last used job ID is fetched from the keyring.",
)
@click.pass_context
def get(ctx, job: str):
    """Retrieve and process job information from AWS Lambda."""

    # The keyring library saves the job_id from the last run job so that Nathan
    # can easily check the status of the last job without having to remember or paste in the job_id.
    # the keystore is only accessible by the user running the CLI, and it's the native keystore for the system.
    if job is None:
        job = keyring.get_password("ndnp_openocr", "job_id")
        if job is None:
            print("[red]No job ID provided and none found in keyring. Exiting.")
            return
        else:
            print(f"[green]Using job ID from keyring: {job}")
    else:
        keyring.set_password("ndnp_openocr", "job_id", job)

    # Setup AWS Lambda client
    lambda_client = boto3.client("lambda", region_name=config.AWS_REGION)
    console = Console()
    print("JOB ID: ", job)
    payload = {"pathParameters": {"jobName": job}}

    try:
        # Invoke Lambda function to get job status
        response = lambda_client.invoke(
            FunctionName=ctx.obj['config']["GET_JOB_ARN"],
            InvocationType="RequestResponse",
            Payload=json.dumps(payload).encode("utf-8"),
        )
        response_payload = json.loads(response["Payload"].read())
        body = json.loads(response_payload.get("body", "{}"))
        console.print_json(json.dumps(body, indent=2))

    except Exception as e:
        print(f"[red]Failed to trigger Lambda function: {e}")

    return ctx


@click.command(name="delete")
@click.option(
    "--job-id",
    help="The job ID to delete from S3. Uses the stored job ID if not provided.",
)
@click.option(
    "--output-dir",
    help="The local directory to delete. Uses the stored output directory if not provided.",
)
@click.pass_context
def delete(ctx, job_id, output_dir):
    """Deletes the S3 directory for the given job_id and the local output_dir."""
    # Fetch stored values if not provided
    stored_config = ctx.obj["config"]
    job_id = job_id or stored_config.get("job_id")
    output_dir = output_dir or stored_config.get("output_dir")

    if not job_id:
        print("[red]No job ID provided or found. Exiting.")
        return

    if not output_dir:
        print("[red]No output directory provided or found. Exiting.")
        return

    # Confirmation prompt before deleting
    if click.confirm(
        f"Are you sure you want to delete S3 directory for job_id: {job_id} and local directory: {output_dir}?"
    ):
        bucket_name = ctx.obj['config']["OUTPUT_BUCKET_NAME"]

        # Delete S3 directory
        s3 = boto3.resource("s3", region_name=config.AWS_REGION)
        bucket = s3.Bucket(bucket_name)
        prefix = f"{job_id}/"  # Assuming the job_id is the prefix for the files in S3
        try:
            bucket.objects.filter(Prefix=prefix).delete()
            print(f"[green]Successfully deleted S3 directory for job_id: {job_id}")
        except boto3.ClientError as e:
            print(
                f"[red]Failed to delete S3 directory for job_id: {job_id}. Error: {e}"
            )

        # Delete local directory
        try:
            shutil.rmtree(output_dir)
            print(f"[green]Successfully deleted local directory: {output_dir}")
        except OSError as e:
            print(f"[red]Failed to delete local directory: {output_dir}. Error: {e}")

    else:
        print("[yellow]Deletion canceled.")


@click.command(name="job_info")
@click.pass_context
def job_info(ctx):
    """Prints out the current job information."""
    config = ctx.obj["config"]
    job_id = config.get("job_id") or keyring.get_password("ndnp_openocr", "job_id")
    output_dir = config.get("output_dir") or keyring.get_password(
        "ndnp_openocr", "output_dir"
    )

    if not job_id and not output_dir:
        print("[yellow]No current job information found.")
    else:
        print(f"[green]Current Job ID: [bold]{job_id if job_id else 'Not specified'}")
        print(
            f"[green]Output Directory: [bold]{output_dir if output_dir else 'Not specified'}"
        )


@click.command()
@click.option(
    "--batch_name",
    default="",
    help="The batch_name in loc-preservation bucket to reprocess.",
)
@click.option(
    "--bucket",
    default="loc-preservation",
    help="The s3 bucket that the batch is located in.",
)
@click.option(
    "--segmentation/--no-segmentation",
    default=False,
    help="Enable segmentation based OCR processing.",
)
@click.option(
    "--img-extension",
    default="tif",
    type=click.Choice(["jp2", "tif"], case_sensitive=False),
    help="Image file extension to process: 'jp2' or 'tif' (default: tif).",
)
@click.pass_context
def reprocess(ctx, batch_name: str, bucket: str, segmentation: bool, img_extension: str):
    """Command to kick off reprocessing job for a certain S3 NDNP batch."""
    if not batch_name:
        print("[red]No batch_name provided. Exiting.")
        return
    ctx = reprocess_batch(ctx, batch_name, bucket, segmentation, img_extension)


cli.add_command(sync)
cli.add_command(reprocess)
cli.add_command(get)
cli.add_command(job_info)
cli.add_command(delete)

if __name__ == "__main__":
    cli()
