import boto3
import click
import requests
from helpers import sync_s3_batch
import json
import time
import logging

logger = logging.getLogger(__name__)


@click.group()
@click.pass_context
def cli(ctx):
    """Initialize command line interface with context settings for bucket, queue, and scheduler ARN."""
    # Initialize the context dict
    ctx.ensure_object(dict)
    # Store bucket in the context
    ctx.obj["INPUT_BUCKET_NAME"] = "loc-preservation"
    ctx.obj["OUTPUT_BUCKET_NAME"] = "ndnp-open-ocr-output-bucket-test"
    ctx.obj[
        "QUEUE_URL"
    ] = "https://sqs.us-east-1.amazonaws.com/342134162356/ndnp-open-ocr-queue"
    ctx.obj[
        "SCHEDULER_ARN"
    ] = "arn:aws:lambda:us-east-2:342134162356:function:ndnp-open-ocr-scheduler-lambda-function-dev"


@click.command()
@click.option("--prefix", default="", help="The prefix in S3 bucket to filter files.")
@click.option(
    "--output-dir", default=".", help="The directory to output the new files to."
)
@click.option(
    "--overwrite", is_flag=True, default=False, help="Overwrite existing files."
)
@click.option("--local-batch", default="", help="The path to local batch data.")
@click.pass_context
def sync(ctx, prefix, output_dir, overwrite, local_batch):
    """Creates a copy of a local NDNP batch, and replaces old PDFs and ALTO files with new PDFs and ALTOs generated by NDNP Open OCR pipeline (outputted to S3)."""

    # Get bucket from the context
    bucket = ctx.obj["OUTPUT_BUCKET_NAME"]
    print(bucket)
    sync_s3_batch(bucket, prefix, output_dir, overwrite, local_batch)


def reprocess_batch(ctx, prefix, bucket):
    """Kicks off reprocessing job for a certain S3 NDNP batch."""
    lambda_client = boto3.client("lambda")
    payload = {
        "pathParameters": {
            "prefix": prefix,
            "bucketName": bucket,
        }
    }
    try:
        # Async invoke the scheduler Lambda function passing the prefix and bucket name
        # as path parameters (modeled from API Gateway request, should be changed later).
        response = lambda_client.invoke(
            FunctionName=ctx.obj["SCHEDULER_ARN"],
            InvocationType="RequestResponse",
            Payload=json.dumps(payload).encode("utf-8"),
        )
        response_payload = json.loads(response["Payload"].read())

        print(response_payload)

        ctx.obj["PREFIX"] = response_payload["prefix"]
        print(ctx.obj["PREFIX"])

    except Exception as e:
        print(f"Failed to trigger Lambda function: {e}")

    return ctx


@click.command()
@click.option(
    "--prefix",
    default="",
    help="The prefix to the batch in the bucket ../.../batch_dlc.../",
)
@click.option(
    "--bucket", default="", help="The s3 bucket that the batch is located in."
)
@click.pass_context
def reprocess(ctx, prefix, bucket):
    """Command to kick off reprocessing job for a certain S3 NDNP batch."""
    ctx = reprocess_batch(ctx, prefix, bucket)


@click.command()
@click.option(
    "--output-dir", default=".", help="The directory to output the new files to."
)
@click.option(
    "--overwrite", is_flag=True, default=False, help="Overwrite existing files."
)
@click.option("--local-batch", default="", help="The path to local batch data.")
@click.option("--batch", default="", help="The batch argument to pass to the API.")
@click.pass_context
def reprocess_and_download(ctx, output_dir, overwrite, local_batch, batch):
    """Kicks off reprocessing job for a certain S3 NDNP batch, then waits for the job to finish and syncs the results."""

    ctx = reprocess_batch(ctx, batch)

    # # Create SQS client
    sqs = boto3.client("sqs")
    # # Set your SQS queue URL
    queue_url = ctx.obj["QUEUE_URL"]
    prefix = ctx.obj["PREFIX"]

    print("Launched reprocessing job. Now waiting for completion...")

    time.sleep(30)

    # Poll the queue until it's clear -- we are assuming that
    # only 1 batch is being processed at a time!
    while True:
        # Get the current count of messages in the queue
        attributes = sqs.get_queue_attributes(
            QueueUrl=queue_url,
            AttributeNames=[
                "ApproximateNumberOfMessages",
                "ApproximateNumberOfMessagesNotVisible",
            ],
        )
        message_count = int(
            attributes["Attributes"]["ApproximateNumberOfMessagesNotVisible"]
        )

        if message_count == 0:
            # If batch processing complete, break
            print("NDNP batch processing is complete!")
            break
        else:
            # If not, wait a while and then check again
            print(
                f"Waiting for NDNP queue to clear: {message_count} issues remaining to be processed."
            )
            time.sleep(60)

    # Once the queue is clear, sync the results
    bucket = ctx.obj["OUTPUT_BUCKET_NAME"]
    print(bucket)
    sync_s3_batch(bucket, prefix, output_dir, overwrite, local_batch)


@click.command()
@click.option("--prefix", default="", help="The prefix in S3 bucket to filter files.")
@click.pass_context
def list_files(ctx, bucket, prefix):
    """List files in the S3 bucket, optionally filtered by a prefix."""

    # Get bucket from the context
    bucket = ctx.obj["OUTPUT_BUCKET_NAME"]

    # Create an S3 client
    s3 = boto3.client("s3")

    try:
        # Call S3 to list current objects in the bucket with the given prefix
        response = s3.list_objects_v2(Bucket=bucket, Prefix=prefix)

        # If the response contains 'Contents', print the keys, else print a message
        if "Contents" in response:
            for item in response["Contents"]:
                print(item["Key"])
        else:
            print("No items in this bucket with the specified prefix.")

    except Exception as e:
        print(f"An error occurred: {e}")


cli.add_command(reprocess_and_download)
cli.add_command(sync)
cli.add_command(reprocess)

if __name__ == "__main__":
    cli()
