import boto3
import click
import requests
from helpers import sync_s3_batch, find_missing_pdfs
import json
import time
import logging
import os
logger = logging.getLogger(__name__)


@click.group()
@click.pass_context
def cli(ctx):
    """Initialize command line interface with context settings for bucket, queue, and scheduler ARN."""
    # Initialize the context dict (these probably should somehow be populated by Terraform in the future...)
    ctx.ensure_object(dict)
    # Store bucket in the context (change to ndnp-open-ocr-output-bucket-test for testing purposes)
    ctx.obj["INPUT_BUCKET_NAME"] = "loc-preservation"
    ctx.obj["OUTPUT_BUCKET_NAME"] = "ndnp-open-ocr-output-bucket-test"
    ctx.obj[
        "QUEUE_URL"
    ] = "https://sqs.us-east-1.amazonaws.com/342134162356/ndnp-open-ocr-queue"
    ctx.obj[
        "SCHEDULER_ARN"
    ] = "arn:aws:lambda:us-east-2:342134162356:function:ndnp-open-ocr-scheduler-lambda-function-dev"


@click.command()
@click.option("--prefix", default="", help="The prefix in S3 bucket to filter files.")
@click.option(
    "--output-dir", default=".", help="The directory to output the new files to."
)
@click.option(
    "--overwrite", is_flag=True, default=False, help="Overwrite existing files."
)
@click.option("--local-batch", default="", help="The path to local batch data.")
@click.pass_context
def sync(ctx, prefix: str, output_dir: str, overwrite: bool, local_batch: str):
    """Creates a copy of a local NDNP batch, and replaces old PDFs and ALTO files with new PDFs and ALTOs generated by NDNP Open OCR pipeline (outputted to S3)."""

    # Get bucket from the context
    bucket = ctx.obj["OUTPUT_BUCKET_NAME"]
    print(bucket)
    sync_s3_batch(bucket, prefix, output_dir, overwrite, local_batch)


def reprocess_batch(ctx, batch_name: str, bucket: str):
    """Kicks off reprocessing job for a certain S3 NDNP batch."""
    lambda_client = boto3.client("lambda")
    prefix = os.path.join("loc-preservation/lcbp/ndnp/dlc/", batch_name)
    payload = {
        "pathParameters": {
            "prefix": prefix,
            "bucketName": bucket,
        }
    }
    try:
        # Async invoke the scheduler Lambda function passing the prefix and bucket name
        # as path parameters (modeled from API Gateway request, should be changed later).
        response = lambda_client.invoke(
            FunctionName=ctx.obj["SCHEDULER_ARN"],
            InvocationType="RequestResponse",
            Payload=json.dumps(payload).encode("utf-8"),
        )
        response_payload = json.loads(response["Payload"].read())

        print(response_payload)

        ctx.obj["PREFIX"] = response_payload["prefix"]
        print(ctx.obj["PREFIX"])

    except Exception as e:
        print(f"Failed to trigger Lambda function: {e}")

    return ctx


@click.command()
@click.option(
    "--batch_name",
    default="",
    help="The batch_name in loc-preservation bucket to reprocess.",
)
@click.option(
    "--bucket", default="", help="The s3 bucket that the batch is located in."
)
@click.pass_context
def reprocess(ctx, prefix: str, bucket: str):
    """Command to kick off reprocessing job for a certain S3 NDNP batch."""
    ctx = reprocess_batch(ctx, prefix, bucket)


@click.command()
@click.option("--output_prefix", default="", help="The prefix in the output bucket")
@click.pass_context
def get_missing(ctx, output_prefix: str):
    """List files missing from S3 output bucket. The output prefix can be used
        to surmise the original input prefix"""

    input_prefix = output_prefix.split("__")[0]

    missing_pdfs = find_missing_pdfs(
        ctx.obj["INPUT_BUCKET_NAME"],
        input_prefix,
        ctx.obj["OUTPUT_BUCKET_NAME"],
        output_prefix,
    )
    print(missing_pdfs)


cli.add_command(sync)
cli.add_command(reprocess)
cli.add_command(get_missing)

if __name__ == "__main__":
    cli()
