from bs4 import NavigableString, BeautifulSoup, Tag
import exiftool
import subprocess
import os
import shutil
import pikepdf
import pytesseract
import datetime
import cv2
from enum import Enum
from xml.etree import ElementTree as ET
import logging
from datetime import datetime
import re
from tempfile import NamedTemporaryFile
import xml.sax.saxutils as saxutils
from ndnp_open_ocr.segmenter import segment_page, merge_alto_region_xmls
from PIL import Image
from reportlab.pdfgen import canvas


logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


class AltoProcessor:
    """Class for postprocessing the ALTO files generated by Tesseract and making them
    compliant with NDNP specificiations."""

    def __init__(self, input_file):
        self.input_file = input_file
        with open(input_file, "r") as f:
            content = f.read()
        self.soup = BeautifulSoup(content, "lxml-xml")

    def add_description_tags(self):
        """Add NDNP Open OCR description tags to the output ALTO file."""
        description = self.soup.find("Description")

        software_name = "Tesseract Open Source OCR Engine"
        software_version = str(pytesseract.get_tesseract_version())

        ocr_processing = self.soup.find("OCRProcessing")

        # Replace tesseract library/vendor info... with the tags below
        ocr_processing_step = self.soup.find("ocrProcessingStep")
        if ocr_processing_step is not None:
            processing_software = ocr_processing_step.find("processingSoftware")
            if processing_software is not None:
                software_name_tag = processing_software.find("softwareName")
                if software_name_tag is not None:
                    software_name_tag.string = software_name
                else:
                    software_name_tag = self.soup.new_tag("softwareName")
                    software_name_tag.string = software_name
                    processing_software.append(software_name_tag)

                software_version_tag = processing_software.find("softwareVersion")
                if software_version_tag is not None:
                    software_version_tag.string = software_version
                else:
                    software_version_tag = self.soup.new_tag("softwareVersion")
                    software_version_tag.string = software_version
                    processing_software.append(software_version_tag)

        # Add postProcessingStep element and its children
        post_processing_step = self.soup.new_tag("postProcessingStep")
        description.append(post_processing_step)

        processing_date_time = self.soup.new_tag("processingDateTime")
        processing_date_time.string = datetime.now().isoformat()
        post_processing_step.append(processing_date_time)

        processing_agency = self.soup.new_tag("processingAgency")
        processing_agency.string = "Library of Congress"
        post_processing_step.append(processing_agency)

        processing_software = self.soup.new_tag("processingSoftware")
        post_processing_step.append(processing_software)

        software_creator = self.soup.new_tag("softwareCreator")
        software_creator.string = "Library of Congress"
        processing_software.append(software_creator)

        software_name = self.soup.new_tag("softwareName")
        software_name.string = "ndnp-open-ocr"
        processing_software.append(software_name)

        software_version = self.soup.new_tag("softwareVersion")
        software_version.string = "1.1"
        processing_software.append(software_version)

        application_description = self.soup.new_tag("applicationDescription")
        application_description.string = (
            "An open-source OCR reprocessing pipeline developed by the Library of "
            "Congress for NDNP data. The pipeline uses advanced segmentation models "
            "and custom post-processing steps to create new NDNP-compliant PDF and "
            "ALTO files."
        )
        processing_software.append(application_description)

        ocr_processing.append(post_processing_step)

    # Convert measurement units to inch1200 from pixels in the ALTO file.
    def convert_pixels_to_inches(self, dpi):
        """
        Update all HEIGHT, WIDTH, HPOS, VPOS attributes in the ALTO (via self.soup)
        by scaling from pixel units at `dpi` to inch1200 units, rounding only once.
        """
        # switch the measurement type in the header
        measurement_unit = self.soup.find("MeasurementUnit")
        measurement_unit.string = "inch1200"

        attributes_to_convert = ["HEIGHT", "WIDTH", "HPOS", "VPOS"]

        def has_required_attrs(element):
            for attr in attributes_to_convert:
                if element.has_attr(attr):
                    return True
            return False

        # walk every relevant tag…
        for element in self.soup.find_all(has_required_attrs):
            for attribute in attributes_to_convert:
                if element.has_attr(attribute):
                    pixel_value = int(element[attribute])
                    inch1200_value = round(float(pixel_value * 1200 / dpi[0]))
                    element[attribute] = str(inch1200_value)

    def add_textblock_language(self, language="eng"):
        """Add a language attribute to each TextBlock in the ALTO file."""
        for block in self.soup.find_all("TextBlock"):
            block["LANG"] = language

    def fix_alto_file_hyphenation(self):
        """Replaces HYP tag with appropriate SUBS_CONTENT tags, per NDNP specs."""
        try:
            soup = self.soup

            # Find all TextLines where the content is equal to "Content"
            text_lines = soup.find_all("TextLine")

            for index, line in enumerate(text_lines):
                hyp_tag = soup.new_tag("HYP", attrs={"CONTENT": "-"})
                strings = line.find_all("String")

                # If there are no strings in this line, then there are no hyphens to fix. Exit function in this case.
                if len(strings) == 0:
                    return
                last_string = strings[-1]
                content = last_string.get("CONTENT")

                # Line-to-Line Hyphenation Check: If the last string ends with a hyphen, it means that there is a linebreak and the other portion of the hyphenation is in the next line
                if content.endswith("-") and len(content) > 1:
                    next_line = text_lines[index + 1]
                    next_line_string = next_line.find_all("String")[0]

                    # Insert HypTag at end of last_string line
                    line.append(hyp_tag)
                    last_string["CONTENT"] = last_string.get("CONTENT").replace("-", "")
                    combined_word = last_string.get("CONTENT") + next_line_string.get(
                        "CONTENT"
                    )
                    last_string["SUBS_CONTENT"] = combined_word
                    next_line_string["SUBS_CONTENT"] = combined_word
                    last_string["SUBS_TYPE"] = "HypPart1"
                    next_line_string["SUBS_TYPE"] = "HypPart2"
        except Exception as e:
            logger.error(f"ALTO file hyphenation fix failed: {e}")

    def save(self, output_file):
        """Write the whole ALTO XML with 2-space indentation,
        and no line-breaks inside element text values. This is essential for 2 primary reasons: 
        1. XML validation tools will fail if there are special charactersin the text values.
        2. We need the formatting to be consistent with ALTO specifications, which format the headers and body differently.
        """
        def escape_xml_attr(value):
            return saxutils.quoteattr(str(value))

        def escape_xml_text(value):
            return saxutils.escape(str(value))

        def write_tag(node, f, level=0):
            indent = "  " * level

            # build attribute string with escaped values
            attrs = "".join(f' {k}={escape_xml_attr(v)}' for k, v in node.attrs.items())

            # filter out pure-whitespace text nodes
            children = [c for c in node.contents
                        if not (isinstance(c, NavigableString) and not c.strip())]

            # no content → self-close
            if not children:
                f.write(f"{indent}<{node.name}{attrs}/>\n")
                return

            # single text node → inline
            if len(children) == 1 and isinstance(children[0], NavigableString):
                text = escape_xml_text(children[0].strip())
                f.write(f"{indent}<{node.name}{attrs}>{text}</{node.name}>\n")
                return

            # otherwise, open tag, recurse children, close tag
            f.write(f"{indent}<{node.name}{attrs}>\n")
            for c in children:
                if isinstance(c, Tag):
                    write_tag(c, f, level + 1)
                else:  # a NavigableString with real text
                    text = escape_xml_text(c.strip())
                    if text:
                        f.write(f"{indent}  {text}\n")
            f.write(f"{indent}</{node.name}>\n")

        alto = self.soup.find("alto")
        with open(output_file, "w", encoding="utf-8") as f:
            f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
            write_tag(alto, f)


class PDFProcessor:
    """Responsible for postprocessing the PDFs that are generated by
    Tesseract as part of NDNP Open OCR reprocessing pipeline."""

    def __init__(self, old_pdf, new_pdf, postprocessed_pdf):
        self.old_pdf = old_pdf
        self.new_pdf = new_pdf
        self.postprocessed_pdf = postprocessed_pdf

    def transfer_xmp(self):
        """Transfer necessary XMP tags (Description, Title, etc...) from the old PDF to the new PDF that's
        generated by the NDNP Open OCR pipeline."""
        try:
            with exiftool.ExifToolAlpha() as et:

                new_tags = et.get_tags(self.postprocessed_pdf, tags=None)[0]

                et.copy_tags(self.old_pdf, self.postprocessed_pdf)

                old_tags = et.get_tags(self.old_pdf, tags=None)[0]
                metadata = et.get_metadata(self.old_pdf)
                logging.info("{} metadata: {}".format(self.old_pdf, metadata))

                title_tag = None
                title_key_list = list(
                    filter(lambda x: x.startswith("XMP:Title"), old_tags)
                )
                if len(title_key_list) >= 1:
                    title_tag = old_tags[title_key_list[0]]

                if title_tag:
                    et.set_tags(
                        self.postprocessed_pdf,
                        {"Title": title_tag, "XMP:Title-en": title_tag},
                    )

                description_value = old_tags.get(
                    "XMP:Description-en", old_tags.get("XMP:Description", None)
                )

                logging.info(f"New Tags from PDF: {new_tags}")

            # Use the XMP:Identifier from old_tags if available
            identifier_to_use = old_tags.get("XMP:Identifier", "XMP-dc:Idenfitifer")
            updated_tags = {
                "XMP:CreateDate": new_tags["File:FileModifyDate"][0:14],
                "XMP:ModifyDate": new_tags["File:FileModifyDate"][0:14],
                "PDF:CreateDate": new_tags["File:FileModifyDate"][0:14],
                "PDF:ModifyDate": new_tags["File:FileModifyDate"][0:14],
                "XMP:Creator": "",
                "PDF:Producer": new_tags["PDF:Producer"],
                "XMP:Description": description_value,
                "PDF:Creator": "ndnp-open-ocr",
                "XMP:Author": "",
                "PDF:Subject": "",
                "XMP:Identifier": identifier_to_use,
            }

            et.set_tags(
                self.postprocessed_pdf,
                updated_tags,
            )
        except Exception as e:
            logging.error(
                "Failure transferring XMP data from {} to {}: {}".format(
                    self.old_pdf, self.postprocessed_pdf, e
                )
            )
            return False

    def postprocess_pdf(self):
        """Set resolution, Display type, etc... on final PDF output"""
        current_directory = os.path.dirname(os.path.abspath(__file__))
        pdf_marks_path = os.path.join(current_directory, "pdf_marks.txt")
        args = [
            "gs",
            "-q",
            "-dNOPAUSE",
            "-dBATCH",
            "-dFastWebView=true",
            f"-sOutputFile={self.postprocessed_pdf}",
            "-sDEVICE=pdfwrite",
            "-dDownsampleColorImages=true",
            "-dDownsampleGrayImages=true",
            "-dDownsampleMonoImages=true",
            "-dColorImageResolution=150",
            "-dGrayImageResolution=150",
            "-dMonoImageResolution=150",
            "-dColorImageDownsampleThreshold=1.0",
            "-dGrayImageDownsampleThreshold=1.0",
            "-dMonoImageDownsampleThreshold=1.0",
            "-dProcessDSCComments=false",
            "-dAutoFilterColorImages=false",
            "-dAutoFilterGrayImages=false",
            "-dColorImageFilter=/DCTEncode",
            "-dGrayImageFilter=/DCTEncode",
            self.new_pdf,
            pdf_marks_path,
        ]

        result = subprocess.run(args, check=True)
        logging.info("stdout: %s", result.stdout)
        logging.error("stderr: %s", result.stderr)

        if os.path.isfile(self.new_pdf):
            logging.info("Output file exists and is a regular file: {self.new_pdf}")
        else:
            logging.info("Output file does not exist or is not a regular file.")

    def linearize_pdf(self):
        """Linearize the final output PDF"""
        try:
            with pikepdf.Pdf.open(
                self.postprocessed_pdf, allow_overwriting_input=True
            ) as pdf:
                pdf.save(self.postprocessed_pdf, linearize=True)
        except Exception as e:
            logging.error(f"PDF Linearization failed: {self.postprocessed_pdf} {e}")


class PreprocessingMethod(Enum):
    """Preprocessing options for input image to Tesseract"""

    ADAPTIVE = "adaptive"
    BINARY = "binary"
    OTSU = "otsu"
    ORIGINAL = "original"


class OCRProcessor:
    """Class to run entire OCR reprocessing job on a single file.
    It takes the input_filepath and the output_path in as input, where input_filepath is the
    location of the TIFF file for the issue on the system, and output_path is where you want
    the output directory structure written into (mirroring input structure)."""

    def __init__(
        self,
        input_file_path,
        output_path,
        preprocessing_method=PreprocessingMethod.ORIGINAL,
        use_segmenter=False,
        layout_model=None,
        line_model=None,
    ):
        self.input_file_path = input_file_path
        self.input_dir = os.path.dirname(self.input_file_path)
        self.output_path = output_path
        self.full_height = True
        self.preprocessing_method = preprocessing_method
        self.use_segmenter = use_segmenter
        self.layout_model = layout_model
        self.line_model = line_model

    def _get_file_name(self):
        return os.path.splitext(os.path.basename(self.input_file_path))[0]

    def _get_new_pdf_path(self):
        """The PDF that is outputted by Tesseract (for files that don't require further preprocessing)"""
        return os.path.join(self.output_path, f"{self._get_file_name()}_new.pdf")

    def get_postprocessed_pdf_path(self):
        """Path to final NDNP Open OCR output PDF"""
        return os.path.join(self.output_path, f"{self._get_file_name()}.pdf")

    def _get_alto_file_path(self):
        return os.path.join(self.output_path, f"{self._get_file_name()}.xml")

    def _get_old_pdf_path(self):
        old_pdf_name = f"{self._get_file_name()}.pdf"
        return os.path.join(self.input_dir, old_pdf_name)

    def _preprocess_image(self):
        """Preprocess the image before it's fed into Tesseract as an input."""

        # Check for JP2 and preprocessing method
        if (
            self.preprocessing_method == PreprocessingMethod.ORIGINAL
            and not self.input_file_path.endswith(".jp2")
        ):
            logging.info("No preprocessing required.")
            return self.input_file_path

        image = cv2.imread(self.input_file_path, cv2.IMREAD_GRAYSCALE)

        # Preprocessing methods
        if self.preprocessing_method == PreprocessingMethod.ADAPTIVE:
            logging.info("PERFORMING ADAPTIVE THRESHOLDING")
            processed_img = cv2.adaptiveThreshold(
                image, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 15, 5
            )
            # Denoise the image
            processed_img = cv2.fastNlMeansDenoising(processed_img, None, 40, 9, 21)
        elif self.preprocessing_method == PreprocessingMethod.BINARY:
            _, processed_img = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)
        elif self.preprocessing_method == PreprocessingMethod.OTSU:
            _, processed_img = cv2.threshold(
                image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU
            )
        else:  # original
            logging.info("USING ORIGINAL IMAGE")
            processed_img = image

        # Write the processed image to a temporary file and return the path
        temp_file_path = self._write_temp_image(processed_img)
        return temp_file_path

    def _write_temp_image(self, image):
        """Write the preprocessed image to a temporary .tif file with lossless compression."""
        temp_file = NamedTemporaryFile(delete=False, suffix=".tif")
        logger.debug("Temporary image file created at %s", temp_file.name)
        cv2.imwrite(temp_file.name, image, [cv2.IMWRITE_TIFF_COMPRESSION, 1])
        return temp_file.name

    def generate_pdf(self):
        """Generate a new OCR PDF, using a given image, with the NDNP Open OCR pipeline. This
        will create a new PDF using Tesseract, with specified preprocessing settings applied to the
        input, then will postprocess the PDF to make it compliant with NDNP specifications for content.
        """
        try:
            logging.info("Generating PDF file")

            if self.use_segmenter:
                logging.info("Generating segmented PDF file")
                pixel_alto_path = os.path.join(
                    self.output_path, f"{self._get_file_name()}_pixel.xml"
                )
                self._build_pdf_from_alto(
                    self.input_file_path, pixel_alto_path, self._get_new_pdf_path()
                )

                if os.path.isfile(pixel_alto_path):
                    os.remove(pixel_alto_path)

            else:
                input_file_path = self._preprocess_image()
                pdf = pytesseract.image_to_pdf_or_hocr(
                    input_file_path, extension="pdf"
                )
                with open(self._get_new_pdf_path(), "w+b") as f:
                    f.write(pdf)
                del pdf

            # PDF Post-processing
            processor = PDFProcessor(
                self._get_old_pdf_path(),  # original PDF
                self._get_new_pdf_path(),  # new PDF
                self.get_postprocessed_pdf_path(),  # where to save final PDF
            )
            processor.postprocess_pdf()
            processor.transfer_xmp()
            processor.linearize_pdf()

            os.remove(self._get_new_pdf_path())
            # Remove pikePdf .pdf_original file output
            os.remove(self.get_postprocessed_pdf_path().replace(".pdf", ".pdf_original"))
            logging.info(f"PDF Generation successful: {self._get_file_name()}")
        except Exception as e:
            logging.error(f"PDF generation failed: {self._get_file_name()} {e}")

    def _build_pdf_from_alto(
        self, tif_path: str, alto_path: str, out_pdf_path: str
    ) -> None:
        """
        Paint the TIFF on a PDF page and overlay invisible text taken
        directly from the ALTO <String> elements so the file is searchable.
        Works with pixel or inch1200 ALTO coordinates.
        """
        # -- open image and derive geometry --------------------------------
        im = Image.open(tif_path)
        w_px, h_px = im.size
        dpi_x, dpi_y = im.info.get("dpi", (300, 300))
        px2pt = 72.0 / dpi_x  # points per pixel
        w_pt = w_px * px2pt
        h_pt = h_px * px2pt

        # -- prepare PDF canvas --------------------------------------------
        c = canvas.Canvas(out_pdf_path, pagesize=(w_pt, h_pt))
        c.drawInlineImage(im, 0, 0, w_pt, h_pt)

        # -- parse ALTO -----------------------------------------------------
        ns = {"a": "http://www.loc.gov/standards/alto/ns-v3#"}
        doc = ET.parse(alto_path)
        mu_elem = doc.find(".//a:MeasurementUnit", ns)
        mu = mu_elem.text.lower() if mu_elem is not None else "pixel"

        # convert ALTO units to image pixels
        def alto_to_px(val: float) -> float:
            return val if mu == "pixel" else val * dpi_x / 1200.0

        # overlay each <String> as invisible text
        for s in doc.findall(".//a:String", ns):
            txt = s.get("CONTENT", "")
            if not txt:
                continue

            # get raw ALTO coords & size
            raw_hpos = float(s.get("HPOS", 0))
            raw_vpos = float(s.get("VPOS", 0))
            raw_ht = float(s.get("HEIGHT", 0))

            # convert to pixels
            hpos_px = alto_to_px(raw_hpos)
            vpos_px = alto_to_px(raw_vpos)
            ht_px = alto_to_px(raw_ht)

            # convert to PDF points
            x_pt = hpos_px * px2pt
            # flip Y-axis: PDF origin is bottom-left
            y_pt = (h_px - vpos_px - ht_px) * px2pt
            fs_pt = max(ht_px * px2pt * 0.9, 1)

            tx = c.beginText()
            tx.setTextRenderMode(3)  # 3 = invisible (no fill/stroke)
            tx.setFont("Times-Roman", fs_pt)  # built-in base-14 font
            tx.setTextOrigin(x_pt, y_pt)
            tx.textLine(txt)
            c.drawText(tx)

        c.showPage()
        c.save()


    def generate_alto(self):
        """Generate a new OCR ALTO file, using a given image, with the NDNP Open OCR pipeline. This
        will create a new ALTO using Tesseract, with specified preprocessing settings applied to the
        input, then will postprocess the ALTO to fix hyphenation, units, etc...
        """
        try:
            logging.info("Generating ALTO file")
            logger.info("Input file path: %s", self.input_file_path)
            if self.use_segmenter:
                logging.info("Segmentation mode enabled")
                logger.debug("Segmenting page into regions")
                regions_dir = os.path.join(
                    self.output_path, f"{self._get_file_name()}_regions"
                )
                os.makedirs(regions_dir, exist_ok=True)
                logger.debug("Regions directory created: %s", regions_dir)

                crops, boxes = segment_page(self.input_file_path)

                logging.info("Detected %d regions", len(crops))
                boxes_dict = {}

                for idx, (rid, crop) in enumerate(crops):
                    logging.debug("OCRing region %s", rid)
                    xml = pytesseract.image_to_alto_xml(crop)
                    xml_path = os.path.join(regions_dir, f"region_{rid}.xml")
                    with open(xml_path, "wb") as f:
                        f.write(xml)
                    logging.debug("Wrote region %s ALTO to %s", rid, xml_path)
                    boxes_dict[str(rid)] = list(boxes[idx])

                merge_alto_region_xmls(
                    source_image_path=self.input_file_path,
                    region_dir=regions_dir,
                    boxes_dict=boxes_dict,
                    output_file=self._get_alto_file_path(),
                )
                logging.info("Composite ALTO written to %s", self._get_alto_file_path())

                # Clean up regions directory once composite ALTO is created
                if os.path.isdir(regions_dir):
                    shutil.rmtree(regions_dir)
            else:
                logging.debug(
                    "Segmentation disabled or utilities missing; using whole image"
                )
                input_file_path = self._preprocess_image()
                xml = pytesseract.image_to_alto_xml(input_file_path)
                with open(self._get_alto_file_path(), "w+b") as f:
                    f.write(xml)

            dpi = (300, 300)

            alto_processor = AltoProcessor(self._get_alto_file_path())
            alto_processor.add_description_tags()
            alto_processor.fix_alto_file_hyphenation()
            alto_processor.add_textblock_language()

            # If using segmenter, save a pixel-unit version of the ALTO *before* unit conversion (for PDF generation in generate_pdf)
            pixel_alto_path = None
            if self.use_segmenter:
                pixel_alto_path = os.path.join(
                    self.output_path, f"{self._get_file_name()}_pixel.xml"
                )
                alto_processor.save(pixel_alto_path)

            # Now convert to inch1200 units
            alto_processor.convert_pixels_to_inches(dpi)
            alto_processor.save(self._get_alto_file_path())

            logging.info(f"ALTO Generation successful: {self._get_file_name()}")
        except Exception as e:
            logging.error(f"ALTO generation failed: {self._get_file_name()} {e}")



    def process(self):
        """OCR an issue in an NDNP batch, generates a new PDF and ALTO file to replace the originals."""
        self.generate_alto()
        self.generate_pdf()
