from bs4 import BeautifulSoup
import exiftool
import subprocess
import os
import pikepdf
import pytesseract
import datetime
import cv2
from enum import Enum
import hocker as hkr
from xml.etree import ElementTree as ET
import logging
from datetime import datetime
import re

logger = logging.getLogger(__name__)


class AltoProcessor:
    """Class for postprocessing the ALTO files generated by Tesseract and making them
    compliant with NDNP specificiations."""

    def __init__(self, input_file):
        self.input_file = input_file
        with open(input_file, "r") as f:
            content = f.read()
        self.soup = BeautifulSoup(content, "lxml-xml")

    def add_description_tags(self):
        """Add NDNP Open OCR description tags to the output ALTO file."""
        description = self.soup.find("Description")

        software_name = "Tesseract Open Source OCR Engine"
        software_version = str(pytesseract.get_tesseract_version())

        ocr_processing = self.soup.find("OCRProcessing")

        # Replace tesseract library/vendor info... with the tags below
        ocr_processing_step = self.soup.find("ocrProcessingStep")
        if ocr_processing_step is not None:
            processing_software = ocr_processing_step.find("processingSoftware")
            if processing_software is not None:
                software_name_tag = processing_software.find("softwareName")
                if software_name_tag is not None:
                    software_name_tag.string = software_name
                else:
                    software_name_tag = self.soup.new_tag("softwareName")
                    software_name_tag.string = software_name
                    processing_software.append(software_name_tag)

                software_version_tag = processing_software.find("softwareVersion")
                if software_version_tag is not None:
                    software_version_tag.string = software_version
                else:
                    software_version_tag = self.soup.new_tag("softwareVersion")
                    software_version_tag.string = software_version
                    processing_software.append(software_version_tag)

        # Add postProcessingStep element and its children
        post_processing_step = self.soup.new_tag("postProcessingStep")
        description.append(post_processing_step)

        processing_date_time = self.soup.new_tag("processingDateTime")
        processing_date_time.string = datetime.now().isoformat()
        post_processing_step.append(processing_date_time)

        processing_agency = self.soup.new_tag("processingAgency")
        processing_agency.string = "Library of Congress"
        post_processing_step.append(processing_agency)

        processing_software = self.soup.new_tag("processingSoftware")
        post_processing_step.append(processing_software)

        software_creator = self.soup.new_tag("softwareCreator")
        software_creator.string = "Library of Congress"
        processing_software.append(software_creator)

        software_name = self.soup.new_tag("softwareName")
        software_name.string = "ndnp-open-ocr"
        processing_software.append(software_name)

        software_version = self.soup.new_tag("softwareVersion")
        software_version.string = "1.0"
        processing_software.append(software_version)

        application_description = self.soup.new_tag("applicationDescription")
        application_description.string = "An OCR and PDF reprocessing pipeline developed by Library of Congress for NDNP-specific data including ALTO end-of-line hyphenation substitution, PDF XMP retention, and NDNP batch merging."
        processing_software.append(application_description)

        ocr_processing.append(post_processing_step)

    # Convert measurement units to inch1200 from pixels in the ALTO file.
    def convert_pixels_to_inches(self, dpi):
        measurement_unit = self.soup.find("MeasurementUnit")
        measurement_unit.string = "inch1200"

        attributes_to_convert = ["HEIGHT", "WIDTH", "HPOS", "VPOS"]

        def has_required_attrs(element):
            for attr in attributes_to_convert:
                if element.has_attr(attr):
                    return True
            return False

        for element in self.soup.find_all(has_required_attrs):
            for attribute in attributes_to_convert:
                if element.has_attr(attribute):
                    pixel_value = int(element[attribute])
                    inch1200_value = round(float(pixel_value * 1200 / dpi[0]))
                    element[attribute] = str(inch1200_value)

    def fix_alto_file_hyphenation(self):
        """Replaces HYP tag with appropriate SUBS_CONTENT tags, per NDNP
        specifications for hyphenation in ALTO files."""
        try:
            with open(self.filepath, "r") as f:
                xml = f.read()
                soup = BeautifulSoup(xml, "xml")

                # Find all TextLines where the content is equal to "Content"
                text_lines = soup.find_all("TextLine")

                for index, line in enumerate(text_lines):
                    hyp_tag = soup.new_tag("HYP", attrs={"CONTENT": "-"})
                    strings = line.find_all("String")

                    # If there are no strings in this line, then there are no hyphens to fix. Exit function in this case.
                    if len(strings) == 0:
                        return
                    last_string = strings[-1]
                    content = last_string.get("CONTENT")

                    # Line-to-Line Hyphenation Check: If the last string ends with a hyphen, it means that there is a linebreak and the other portion of the hyphenation is in the next line
                    if content.endswith("-") and len(content) > 1:
                        next_line = text_lines[index + 1]
                        next_line_string = next_line.find_all("String")[0]

                        # Insert HypTag at end of last_string line
                        line.append(hyp_tag)
                        last_string["CONTENT"] = last_string.get("CONTENT").replace(
                            "-", ""
                        )
                        combined_word = last_string.get(
                            "CONTENT"
                        ) + next_line_string.get("CONTENT")
                        last_string["SUBS_CONTENT"] = combined_word
                        next_line_string["SUBS_CONTENT"] = combined_word
                        last_string["SUBS_TYPE"] = "HypPart1"
                        next_line_string["SUBS_TYPE"] = "HypPart2"

                f.close()

                # Overwrite old ALTO file with the new and fixed XML contents.
                with open(self.filepath, "w") as f:
                    f.write(str(soup))
                    f.close()
        except Exception as e:
            logging.error("ALTO file hyphenation fix failed: {}".format(e))

    def save(self, output_file):
        with open(output_file, "w") as f:
            f.write(str(self.soup))


class PDFProcessor:
    """Responsible for postprocessing the PDFs that are generated by
    Tesseract as part of NDNP Open OCR reprocessing pipeline."""

    def __init__(self, old_pdf, new_pdf, postprocessed_pdf):
        self.old_pdf = old_pdf
        self.new_pdf = new_pdf
        self.postprocessed_pdf = postprocessed_pdf

    def transfer_xmp(self):
        """Transfer necessary XMP tags (Description, Title, etc...) from the old PDF to the new PDF that's
        generated by the NDNP Open OCR pipeline."""
        try:
            with exiftool.ExifToolAlpha() as et:

                new_tags = et.get_tags(self.postprocessed_pdf, tags=None)[0]

                et.copy_tags(self.old_pdf, self.postprocessed_pdf)

                old_tags = et.get_tags(self.old_pdf, tags=None)[0]

                title_tag = None
                title_key_list = list(
                    filter(lambda x: x.startswith("XMP:Title"), old_tags)
                )
                if len(title_key_list) >= 1:
                    title_tag = old_tags[title_key_list[0]]

                if title_tag:
                    et.set_tags(
                        self.postprocessed_pdf,
                        {"Title": title_tag, "XMP:Title-en": title_tag},
                    )

                description_value = old_tags.get(
                    "XMP:Description-en", old_tags.get("XMP:Description", None)
                )

                logging.info(f"New Tags from PDF: {new_tags}")


                # If XMP:Identifier is not in the old PDF tags (like with most), try to parse dc li element, which has
                # been found to be the other contingency.
                if "XMP:Identifier" not in old_tags:
                    logging.info(
                        "No XMP Identifier in original PDF. Try to extract from dc li components."
                    )
                    # Simulated example of extracting a text block from the PDF
                    extracted_text = """
                    <dc:identifier>
                    <rdf:Alt>
                    <rdf:li xml:lang="en">Reel number 00206530753. Sequence number 833.</rdf:li>
                    </rdf:Alt>
                    </dc:identifier>
                    """

                    # Regular expression to find the dc:identifier value
                    dc_identifier_match = re.search(
                        r'<rdf:li xml:lang="en">(.*?)</rdf:li>', extracted_text
                    )

                    # Extract the dc:identifier if found
                    dc_identifier = (
                        dc_identifier_match.group(1) if dc_identifier_match else None
                    )
                    logging.info(
                        "dc_identifier extracted has the value: {}".format(
                            dc_identifier
                        )
                    )

                # Use the XMP:Identifier from old_tags if available, else use the extracted dc:identifier
                identifier_to_use = old_tags.get("XMP:Identifier", dc_identifier)

                updated_tags = {
                    "XMP:CreateDate": new_tags["File:FileModifyDate"][0:14],
                    "XMP:ModifyDate": new_tags["File:FileModifyDate"][0:14],
                    "PDF:CreateDate": new_tags["File:FileModifyDate"][0:14],
                    "PDF:ModifyDate": new_tags["File:FileModifyDate"][0:14],
                    "XMP:Creator": "",
                    "PDF:Producer": new_tags["PDF:Producer"],
                    "XMP:Description": description_value,
                    "PDF:Creator": "ndnp-open-ocr",
                    "XMP:Author": "",
                    "PDF:Subject": "",
                    "XMP:Identifier": identifier_to_use,
                }

                et.set_tags(
                    self.postprocessed_pdf,
                    updated_tags,
                )
        except Exception as e:
            logging.error(
                "Failure transferring XMP data from {} to {}: {}".format(
                    self.old_pdf, self.postprocessed_pdf, e
                )
            )
            return False

    def postprocess_pdf(self):
        """Set resolution, Display type, etc... on final PDF output"""
        current_directory = os.path.dirname(os.path.abspath(__file__))
        pdf_marks_path = os.path.join(current_directory, "pdf_marks.txt")
        args = [
            "gs",
            "-q",
            "-dNOPAUSE",
            "-dBATCH",
            "-dFastWebView=true",
            f"-sOutputFile={self.postprocessed_pdf}",
            "-sDEVICE=pdfwrite",
            "-dDownsampleColorImages=true",
            "-dDownsampleGrayImages=true",
            "-dDownsampleMonoImages=true",
            "-dColorImageResolution=150",
            "-dGrayImageResolution=150",
            "-dMonoImageResolution=150",
            "-dColorImageDownsampleThreshold=1.0",
            "-dGrayImageDownsampleThreshold=1.0",
            "-dMonoImageDownsampleThreshold=1.0",
            "-dProcessDSCComments=false",
            "-dAutoFilterColorImages=false",
            "-dAutoFilterGrayImages=false",
            "-dColorImageFilter=/DCTEncode",
            "-dGrayImageFilter=/DCTEncode",
            self.new_pdf,
            pdf_marks_path,
        ]

        result = subprocess.run(args, check=True)
        logging.info("stdout: %s", result.stdout)
        logging.error("stderr: %s", result.stderr)

        if os.path.isfile(self.new_pdf):
            logging.info("Output file exists and is a regular file: {self.new_pdf}")
        else:
            logging.info("Output file does not exist or is not a regular file.")

    def linearize_pdf(self):
        """Linearize the final output PDF"""
        try:
            with pikepdf.Pdf.open(
                self.postprocessed_pdf, allow_overwriting_input=True
            ) as pdf:
                pdf.save(self.postprocessed_pdf, linearize=True)
        except Exception as e:
            logging.error(f"PDF Linearization failed: {self.postprocessed_pdf} {e}")


class PreprocessingMethod(Enum):
    """Preprocessing options for input image to Tesseract"""

    ADAPTIVE = "adaptive"
    BINARY = "binary"
    OTSU = "otsu"
    ORIGINAL = "original"


class OCRProcessor:
    """Class to run entire OCR reprocessing job on a single file.
    It takes the input_filepath and the output_path in as input, where input_filepath is the
    location of the TIFF file for the issue on the system, and output_path is where you want
    the output directory structure written into (mirroring input structure)."""

    def __init__(
        self,
        input_file_path,
        output_path,
        preprocessing_method=PreprocessingMethod.ORIGINAL,
    ):
        self.input_file_path = input_file_path
        self.input_dir = os.path.dirname(self.input_file_path)
        self.output_path = output_path
        self.full_height = True
        self.preprocessing_method = preprocessing_method

    def _get_file_name(self):
        return os.path.splitext(os.path.basename(self.input_file_path))[0]

    def _get_new_pdf_path(self):
        """The PDF that is outputted by Tesseract (for files that don't require further preprocessing)"""
        return os.path.join(self.output_path, f"{self._get_file_name()}_new.pdf")

    def _get_new_hocr_path(self):
        """For files that require preprocessing to run, this is the path for the HOCR output from
        Tesseract, which is used to create a PDF with the original TIFF image."""
        return os.path.join(self.output_path, f"{self._get_file_name()}_new.hocr")

    def get_postprocessed_pdf_path(self):
        """Path to final NDNP Open OCR output PDF"""
        return os.path.join(self.output_path, f"{self._get_file_name()}.pdf")

    def _get_alto_file_path(self):
        return os.path.join(self.output_path, f"{self._get_file_name()}.xml")

    def _get_old_pdf_path(self):
        old_pdf_name = f"{self._get_file_name()}.pdf"
        return os.path.join(self.input_dir, old_pdf_name)

    def _preprocess_image(self):
        """Preprocess the image before it's fed into Tesseract as an input."""

        image = cv2.imread(self.input_file_path, cv2.IMREAD_GRAYSCALE)

        # Preprocessing methods
        if self.preprocessing_method == PreprocessingMethod.ADAPTIVE:
            logging.info("PERFORMING ADAPTIVE THRESHOLDING")
            processed_img = cv2.adaptiveThreshold(
                image, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 15, 5
            )
            # Denoise the image
            processed_img = cv2.fastNlMeansDenoising(processed_img, None, 40, 9, 21)
        elif self.preprocessing_method == PreprocessingMethod.BINARY:
            _, processed_img = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)
        elif self.preprocessing_method == PreprocessingMethod.OTSU:
            _, processed_img = cv2.threshold(
                image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU
            )
        else:  # original
            logging.info("USING ORIGINAL IMAGE")
            processed_img = image

        return processed_img

    def generate_pdf(self):
        """Generate a new OCR PDF, using a given image, with the NDNP Open OCR pipeline. This
        will create a new PDF using Tesseract, with specified preprocessing settings applied to the
        input, then will postprocess the PDF to make it compliant with NDNP specifications for content.
        """
        try:
            logging.info("Generating PDF file")
            temp_gray_path = self._preprocess_image()

            if self.preprocessing_method == PreprocessingMethod.ORIGINAL:
                # # Generate PDF from grayscale image
                pdf = pytesseract.image_to_pdf_or_hocr(
                    self.input_file_path, extension="pdf"
                )
                with open(self._get_new_pdf_path(), "w+b") as f:
                    f.write(pdf)
                del pdf
            else:
                # For preprocessed images, we have to overlay the new HOCR onto the original image ourselves.
                # instead of relying solely on Tesseract.
                hocr = pytesseract.image_to_pdf_or_hocr(
                    temp_gray_path, extension="hocr", config="-l eng"
                ).decode()
                with open(self._get_new_hocr_path(), "w") as f:
                    f.write(hocr)
                del hocr

                # Specify the element in the hocr file to use as the text
                hocr = hkr.HOCRCombiner(
                    "ocrx_word"
                )  # For tesseract outputs, it is 'ocrx_word'
                # Specify the hocr and image path
                hocr.locate_image(self.input_file_path)
                hocr.locate_hocr(self._get_new_hocr_path())

                # Generate new PDF based on original TIFF and new HOCR image.
                # This is the same as the original PDF, but with the new HOCR overlaid on top.
                hocr.to_pdf(self._get_new_pdf_path())

                tree = ET.parse(self._get_new_hocr_path())
                root = tree.getroot()

                # Search for 'ocrx_word' tags (Tesseract-specific tags for the words)
                words = root.findall(".//span[@class='ocrx_word']")

                # Confirm that text is picked up by Tesseract, if it isn't, then raise Exception.
                if len(words) > 0:
                    raise Exception("PDF Creation Failed: No Text Detected in PDF File")

                os.remove(self._get_new_hocr_path())

            # os.remove(temp_gray_path)
            processor = PDFProcessor(
                self._get_old_pdf_path(),  # original PDF
                self._get_new_pdf_path(),  # new PDF
                self.get_postprocessed_pdf_path(),  # where to save final PDF, after all post-processing steps are complete.
            )
            processor.postprocess_pdf()
            processor.transfer_xmp()
            processor.linearize_pdf()

            os.remove(self._get_new_pdf_path())
            # Remove pikePdf .pdf_original file output
            os.remove(
                self.get_postprocessed_pdf_path().replace(".pdf", ".pdf_original")
            )
            logging.info(f"PDF Generation successful: {self._get_file_name()}")
        except Exception as e:
            logging.error(f"PDF generation failed: {self._get_file_name()} {e}")

    def generate_alto(self):
        """Generate a new OCR ALTO file, using a given image, with the NDNP Open OCR pipeline. This
        will create a new ALTO using Tesseract, with specified preprocessing settings applied to the
        input, then will postprocess the ALTO to fix hyphenation, units, etc...
        """
        try:
            # Preprocess with CV2.
            logging.info("Generating ALTO file")
            xml = pytesseract.image_to_alto_xml(self.input_file_path)
            with open(self._get_alto_file_path(), "w+b") as f:
                f.write(xml)

            # image = Image.fromarray(temp_gray_path)
            # dpi = image.info.get("dpi", (96, 96))
            dpi = (300, 300)

            alto_processor = AltoProcessor(self._get_alto_file_path())
            alto_processor.add_description_tags()
            alto_processor.convert_pixels_to_inches(dpi)
            alto_processor.save(self._get_alto_file_path())
            del xml
            logging.info(f"ALTO Generation successful: {self._get_file_name()}")
        except Exception as e:
            logging.error(f"ALTO generation failed: {self._get_file_name()} {e}")

    def process(self):
        """OCR an issue in an NDNP batch, generates a new PDF and ALTO file to replace the originals."""
        self.generate_pdf()
        self.generate_alto()
