import boto3
import click
import requests
from helpers import sync_s3_batch
import json
import time
@click.group()
@click.pass_context
def cli(ctx):
    """Command line interface."""
    # Initialize the context dict
    ctx.ensure_object(dict)
    # Store bucket in the context
    ctx.obj['BUCKET'] = "ndnp-open-ocr-output-bucket-test"
    ctx.obj['QUEUE_URL'] = "https://sqs.us-east-1.amazonaws.com/342134162356/ndnp-open-ocr-queue"
    ctx.obj['API_URL'] = "https://o26oj5w54d.execute-api.us-east-1.amazonaws.com/dev/"

@click.command()
@click.option('--prefix', default='', help='The prefix in S3 bucket to filter files.')
@click.option('--output-dir', default='.', help='The directory to output the new files to.')
@click.option('--overwrite', is_flag=True, default=False, help='Overwrite existing files.')
@click.option('--local-batch', default='', help='The path to local batch data.')
@click.pass_context
def sync(ctx, prefix, output_dir, overwrite, local_batch):
    """Creates a copy of a local NDNP batch, and replaces old PDFs and ALTO files with new PDFs and ALTOs generated by NDNP Open OCR pipeline (outputted to S3). """

    # Get bucket from the context
    bucket = ctx.obj['BUCKET']
    print(bucket)
    sync_s3_batch(bucket, prefix, output_dir, overwrite, local_batch)


def reprocess_batch(ctx, batch):
    """Kicks off reprocessing job for a certain S3 NDNP batch."""
    api_url = ctx.obj['API_URL']
    response = requests.post(f'{api_url}/{batch}')
    if response.status_code == 200:
        print(f"{response.text}")
        ctx.obj['PREFIX'] = json.loads(response.text)['prefix']
        print(ctx.obj['PREFIX'])
    else:
        print(f"Failed to trigger API endpoint: {api_url}{batch}. Status code: {response.status_code}")
    return ctx


@click.command()
@click.option('--batch', default='', help='The batch argument to pass to the API.')
@click.pass_context
def reprocess(ctx, batch):
    """Command to kick off reprocessing job for a certain S3 NDNP batch."""
    ctx = reprocess_batch(ctx, batch)
@click.command()
@click.option('--output-dir', default='.', help='The directory to output the new files to.')
@click.option('--overwrite', is_flag=True, default=False, help='Overwrite existing files.')
@click.option('--local-batch', default='', help='The path to local batch data.')
@click.option('--batch', default='', help='The batch argument to pass to the API.')
@click.pass_context
def reprocess_and_download(ctx, output_dir, overwrite, local_batch, batch):
    """Kicks off reprocessing job for a certain S3 NDNP batch, then waits for the job to finish and syncs the results."""

    ctx = reprocess_batch(ctx, batch)

    # # Create SQS client
    sqs = boto3.client('sqs')
    # # Set your SQS queue URL
    queue_url = ctx.obj['QUEUE_URL']
    prefix = ctx.obj['PREFIX']

    print("Launched reprocessing job. Now waiting for completion...")

    time.sleep(30)

    # Poll the queue until it's clear
    while True:
        # Get the current count of messages in the queue
        attributes = sqs.get_queue_attributes(
            QueueUrl=queue_url,
            AttributeNames=['ApproximateNumberOfMessages', 'ApproximateNumberOfMessagesNotVisible']
        )
        message_count = int(attributes['Attributes']['ApproximateNumberOfMessagesNotVisible'])

        if message_count == 0:
            # If batch processing complete, break
            print("NDNP batch processing is complete!")
            break
        else:
            # If not, wait a while and then check again
            print(f"Waiting for NDNP queue to clear: {message_count} issues remaining to be processed.")
            time.sleep(60)

    # Once the queue is clear, sync the results
    bucket = ctx.obj['BUCKET']
    print(bucket)
    sync_s3_batch(bucket, prefix, output_dir, overwrite, local_batch)

cli.add_command(reprocess_and_download)
cli.add_command(sync)
cli.add_command(reprocess)

if __name__ == "__main__":
    cli()